env:
  browser: true
  es2021: true

plugins:
  - '@stylistic/js'

extends:
  - 'plugin:@stylistic/js/recommended'

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: off
