env:
  browser: true
  es2021: true

extends:
  - airbnb-base
 #- plugin:@stylistic/js/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - '@stylistic/js'

rules:
  no-console: off
  semi: [error, never]       # запрещаем точку с запятой
  quotes: [error, single]    # одинарные кавычки

