name: Node CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      
      - name: Clone the git repository code
        uses: actions/checkout@v4

     
      - name: setup nodejs
        uses: actions/setup-node@v4
      
        
      - name: Instal dependencies
        run: make install

       
      - name: Run Eslint
        run: make lint

       
      - name: Run tests
        run: make test
